<?php

/**
 * @file
 * Uses the PHPMailer library to send emails via SMTP.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function phpmailer_smtp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.phpmailer_smtp':
      $text = file_get_contents(__DIR__ . '/README.txt');
      return '<pre>' . Html::escape($text) . '</pre>';

    default:
  }
}

/**
 * Implements hook_mail().
 */
function phpmailer_smtp_mail($key, &$message, $params) {
  switch ($key) {
    case 'test':
      $message['subject'] = (string) t('PHPMailer SMTP test email');
      $message['body'][] = (string) t('Your site is properly configured to send emails using the PHPMailer library.');
      break;
  }
}
